---
- name: Create OpenTelemetry Collector directory
  file:
    path: /opt/otelcol
    state: directory
    mode: '0755'

- name: Download OpenTelemetry Collector
  get_url:
    url: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.88.0/otelcol-contrib_0.88.0_linux_amd64.tar.gz
    dest: /tmp/otelcol.tar.gz
    mode: '0644'

- name: Extract OpenTelemetry Collector
  unarchive:
    src: /tmp/otelcol.tar.gz
    dest: /opt/otelcol
    remote_src: yes

- name: Create OpenTelemetry Collector config
  template:
    src: otel-collector-config.yaml.j2
    dest: /opt/otelcol/config.yaml
    mode: '0644'
  notify: Restart OpenTelemetry Collector

- name: Create OpenTelemetry Collector systemd service
  template:
    src: otel-collector.service.j2
    dest: /etc/systemd/system/otel-collector.service
    mode: '0644'
  notify: Restart OpenTelemetry Collector

- name: Start and enable OpenTelemetry Collector
  systemd:
    name: otel-collector
    state: started
    enabled: yes
    daemon_reload: yes

